services:
  # MapStory Web Application
  - type: web
    name: mapstory-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/maps
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false  # Set this manually in Render dashboard

databases:
  - name: mapstory-db
    databaseName: mapstory
    user: mapstory_user
    plan: free 